from typing import SupportsIndex, TypeAlias, Self, Iterator, Union, Any, Literal, Callable, overload, final
from _typeshed import ReadableBuffer
from types import TracebackType
import _cffi_backend
# needed for conditional definitions in FFI, see below
import sys

class _CDataBase:
    def __enter__(self) -> Self: ...
    def __exit__(self, type: type[BaseException] | None, value: BaseException | None, traceback: TracebackType | None, /) -> None: ...

    def __bool__(self) -> bool: ...
    def __hash__(self) -> int: ...

class IntPrimitive(_CDataBase):
    def __int__(self) -> int: ...
    def __eq__(self, other: IntPrimitive, /) -> bool: ...  # type: ignore[override]
    def __ne__(self, other: IntPrimitive, /) -> bool: ...  # type: ignore[override]
    def __ge__(self, other: IntPrimitive, /) -> bool: ...
    def __gt__(self, other: IntPrimitive, /) -> bool: ...
    def __le__(self, other: IntPrimitive, /) -> bool: ...
    def __lt__(self, other: IntPrimitive, /) -> bool: ...

class EnumCData(IntPrimitive):
    pass

class FloatPrimitive(_CDataBase):
    def __int__(self) -> int: ...
    def __float__(self) -> float: ...
    def __eq__(self, other: FloatPrimitive, /) -> bool: ...  # type: ignore[override]
    def __ne__(self, other: FloatPrimitive, /) -> bool: ...  # type: ignore[override]
    def __ge__(self, other: FloatPrimitive, /) -> bool: ...
    def __gt__(self, other: FloatPrimitive, /) -> bool: ...
    def __le__(self, other: FloatPrimitive, /) -> bool: ...
    def __lt__(self, other: FloatPrimitive, /) -> bool: ...

class ComplexPrimitive(_CDataBase):
    def __complex__(self) -> complex: ...
    def __eq__(self, other: ComplexPrimitive, /) -> bool: ...  # type: ignore[override]
    def __ne__(self, other: ComplexPrimitive, /) -> bool: ...  # type: ignore[override]
    def __ge__(self, other: ComplexPrimitive, /) -> bool: ...
    def __gt__(self, other: ComplexPrimitive, /) -> bool: ...
    def __le__(self, other: ComplexPrimitive, /) -> bool: ...
    def __lt__(self, other: ComplexPrimitive, /) -> bool: ...

class PointerBase[T](_CDataBase):
    """ Used for all pointers, including those pointing to unsized types, which have restricted operations. """
    def __eq__(self, other: PointerBase[Any], /) -> bool: ...  # type: ignore[override]
    def __ne__(self, other: PointerBase[Any], /) -> bool: ...  # type: ignore[override]
    def __ge__(self, other: PointerBase[Any], /) -> bool: ...
    def __gt__(self, other: PointerBase[Any], /) -> bool: ...
    def __le__(self, other: PointerBase[Any], /) -> bool: ...
    def __lt__(self, other: PointerBase[Any], /) -> bool: ...

class Pointer[T](PointerBase[T]):
    """ Pointer to a sized type. """
    def __add__(self, other: int, /) -> Pointer[T]: ...
    def __radd__(self, other: int, /) -> Pointer[T]: ...
    @overload
    def __sub__(self, other: int, /) -> Pointer[T]: ...
    @overload
    def __sub__(self, other: Pointer[T], /) -> int: ...
    # FIXME: make cffi actually raise in the unsized case
    @overload
    def __getitem__(self, index: int) -> T: ...
    @overload
    def __getitem__(self, index: slice) -> Array[T]: ...
    @overload
    def __setitem__(self, index: int, value: T) -> None: ...
    @overload
    def __setitem__(self, index: slice, value: Array[T]) -> None: ...

class Array[T](Pointer[T]):
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[T]: ...

@final
class buffer:
    __hash__: ClassVar[None]  # type: ignore[assignment]
    def __new__(cls, cdata: PointerBase[object], size: int = -1) -> Self: ...
    def __buffer__(self, flags: int, /) -> memoryview: ...
    def __eq__(self, other: ReadableBuffer, /) -> bool: ...  # type: ignore[override]
    def __ne__(self, other: ReadableBuffer, /) -> bool: ...  # type: ignore[override]
    def __ge__(self, other: ReadableBuffer, /) -> bool: ...
    def __gt__(self, other: ReadableBuffer, /) -> bool: ...
    def __le__(self, other: ReadableBuffer, /) -> bool: ...
    def __lt__(self, other: ReadableBuffer, /) -> bool: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: Union[SupportsIndex, slice], /) -> bytes: ...
    def __setitem__(self, index: Union[SupportsIndex, slice], value: bytes, /) -> None: ...

# These aliases are to work around pyright complaints.
# Pyright doesn't like it when a class object is defined as an alias
# of a global object with the same name.
_tmp_buffer = buffer

ErrorCallback: TypeAlias = Callable[[Exception, Any, TracebackType], Any]


class types:
    short: TypeAlias = int

    char: TypeAlias = bytes
    ''' bytes of length 1 '''

    class SynthAudioCb(_CDataBase):
        ''' function pointer type:
        .. code-block:: c
            void(*)(int, short *, void *) '''
        def __call__(self, arg1: int, arg2: Pointer[types.short], arg3: PointerBase[object], /) -> None: ...

    SynthDict: TypeAlias = PointerBase[types.struct__SynthDict]

    class struct__SynthDict(_CDataBase):
        ''' struct _SynthDict '''

    SynthDictStr: TypeAlias = Pointer[types.char]

    enum_SynthDictVolume: TypeAlias = int

    SynthDictVolume: TypeAlias = types.enum_SynthDictVolume

    class anon_function_0(_CDataBase):
        ''' function pointer type:
        .. code-block:: c
            void(*)(int, void *) '''
        def __call__(self, arg1: int, arg2: PointerBase[object], /) -> None: ...

    SynthEventCb: TypeAlias = types.anon_function_0

    SynthTextIndexCb: TypeAlias = types.anon_function_0

    SynthWordIndexCb: TypeAlias = types.anon_function_0

    class SynthParamCb(_CDataBase):
        ''' function pointer type:
        .. code-block:: c
            void(*)(enum SynthParamId, int, void *) '''
        def __call__(self, arg1: types.enum_SynthParamId, arg2: int, arg3: PointerBase[object], /) -> None: ...

    enum_SynthParamId: TypeAlias = int

    class SynthPhonemeCb(_CDataBase):
        ''' function pointer type:
        .. code-block:: c
            void(*)(char *, int, void *) '''
        def __call__(self, arg1: Union[Pointer[types.char], bytes], arg2: int, arg3: PointerBase[object], /) -> None: ...

    SynthPtr: TypeAlias = Pointer[types.struct_Synth]

    class struct_Synth(_CDataBase):
        ''' struct Synth (size = 8) '''
        vtable: Pointer[types.struct_Synth_vtable]
        ''' 
        .. code-block:: c
            struct Synth_vtable *vtable; '''

    class struct_Synth_vtable(_CDataBase):
        ''' struct Synth_vtable (size = 312) '''
        __method0: types.anon_function_1
        ''' 
        .. code-block:: c
            void(*__method0)(struct Synth *); '''
        __method1: types.anon_function_1
        ''' 
        .. code-block:: c
            void(*__method1)(struct Synth *); '''
        destroy: types.anon_function_1
        ''' 
        .. code-block:: c
            void(*destroy)(struct Synth *); '''
        init: types.anon_function_2
        ''' 
        .. code-block:: c
            int(*init)(struct Synth *); '''
        __method4: types.anon_function_1
        ''' 
        .. code-block:: c
            void(*__method4)(struct Synth *); '''
        pushText: types.anon_function_3
        ''' 
        .. code-block:: c
            int(*pushText)(struct Synth *, char *); '''
        pushText2: types.anon_function_3
        ''' 
        .. code-block:: c
            int(*pushText2)(struct Synth *, char *); '''
        __method7: types.anon_function_1
        ''' 
        .. code-block:: c
            void(*__method7)(struct Synth *); '''
        __method8: types.anon_function_1
        ''' 
        .. code-block:: c
            void(*__method8)(struct Synth *); '''
        readPhonemes: types.anon_function_4
        ''' 
        .. code-block:: c
            int(*readPhonemes)(struct Synth *, char *, int, int *); '''
        __method10: types.anon_function_1
        ''' 
        .. code-block:: c
            void(*__method10)(struct Synth *); '''
        setFlushing: types.anon_function_5
        ''' 
        .. code-block:: c
            int(*setFlushing)(struct Synth *, _Bool); '''
        prepare: types.anon_function_2
        ''' 
        .. code-block:: c
            int(*prepare)(struct Synth *); '''
        __method13: types.anon_function_1
        ''' 
        .. code-block:: c
            void(*__method13)(struct Synth *); '''
        __method14: types.anon_function_1
        ''' 
        .. code-block:: c
            void(*__method14)(struct Synth *); '''
        __method15: types.anon_function_1
        ''' 
        .. code-block:: c
            void(*__method15)(struct Synth *); '''
        __method16: types.anon_function_1
        ''' 
        .. code-block:: c
            void(*__method16)(struct Synth *); '''
        setCallbackAudio: types.anon_function_6
        ''' 
        .. code-block:: c
            int(*setCallbackAudio)(struct Synth *, void(*)(int, short *, void *), void *); '''
        __method18: types.anon_function_1
        ''' 
        .. code-block:: c
            void(*__method18)(struct Synth *); '''
        setCallbackTextIndex: types.anon_function_7
        ''' 
        .. code-block:: c
            void(*setCallbackTextIndex)(struct Synth *, void(*)(int, void *), void *); '''
        setCallbackEvent: types.anon_function_7
        ''' 
        .. code-block:: c
            void(*setCallbackEvent)(struct Synth *, void(*)(int, void *), void *); '''
        setCallbackPhoneme: types.anon_function_8
        ''' 
        .. code-block:: c
            void(*setCallbackPhoneme)(struct Synth *, void(*)(char *, int, void *), void *); '''
        setCallbackParam: types.anon_function_9
        ''' 
        .. code-block:: c
            void(*setCallbackParam)(struct Synth *, void(*)(enum SynthParamId, int, void *), void *); '''
        pushEvent: types.anon_function_10
        ''' 
        .. code-block:: c
            int(*pushEvent)(struct Synth *, int); '''
        pushEventAt: types.anon_function_11
        ''' 
        .. code-block:: c
            int(*pushEventAt)(struct Synth *, int, int); '''
        setWantWordIndices: types.anon_function_12
        ''' 
        .. code-block:: c
            void(*setWantWordIndices)(struct Synth *, _Bool); '''
        preDestruct: types.anon_function_1
        ''' 
        .. code-block:: c
            void(*preDestruct)(struct Synth *); '''
        dictNew: types.anon_function_13
        ''' 
        .. code-block:: c
            struct _SynthDict *(*dictNew)(struct Synth *); '''
        __method28: types.anon_function_1
        ''' 
        .. code-block:: c
            void(*__method28)(struct Synth *); '''
        dictSetActive: types.anon_function_14
        ''' 
        .. code-block:: c
            void(*dictSetActive)(struct Synth *, struct _SynthDict *); '''
        dictDelete: types.anon_function_14
        ''' 
        .. code-block:: c
            void(*dictDelete)(struct Synth *, struct _SynthDict *); '''
        dictLoad: types.anon_function_15
        ''' 
        .. code-block:: c
            void(*dictLoad)(struct Synth *, struct _SynthDict *, enum SynthDictVolume, char *); '''
        dictSave: types.anon_function_15
        ''' 
        .. code-block:: c
            void(*dictSave)(struct Synth *, struct _SynthDict *, enum SynthDictVolume, char *); '''
        dictUpdate: types.anon_function_16
        ''' 
        .. code-block:: c
            int(*dictUpdate)(struct Synth *, struct _SynthDict *, enum SynthDictVolume, char *, char *); '''
        dictGetFirstEntry: types.anon_function_17
        ''' 
        .. code-block:: c
            void(*dictGetFirstEntry)(struct Synth *, struct _SynthDict *, enum SynthDictVolume, char * *, char * *); '''
        dictGetNextEntry: types.anon_function_17
        ''' 
        .. code-block:: c
            void(*dictGetNextEntry)(struct Synth *, struct _SynthDict *, enum SynthDictVolume, char * *, char * *); '''
        dictLookup: types.anon_function_18
        ''' 
        .. code-block:: c
            char *(*dictLookup)(struct Synth *, struct _SynthDict *, enum SynthDictVolume, char *); '''
        setCallbackWordIndex: types.anon_function_7
        ''' 
        .. code-block:: c
            void(*setCallbackWordIndex)(struct Synth *, void(*)(int, void *), void *); '''
        setCallbackUserIndex: types.anon_function_19
        ''' 
        .. code-block:: c
            void(*setCallbackUserIndex)(struct Synth *, void(*)(void *), void *); '''

    class anon_function_1(_CDataBase):
        ''' function pointer type:
        .. code-block:: c
            void(*)(struct Synth *) '''
        def __call__(self, arg1: Pointer[types.struct_Synth], /) -> None: ...

    class anon_function_2(_CDataBase):
        ''' function pointer type:
        .. code-block:: c
            int(*)(struct Synth *) '''
        def __call__(self, arg1: Pointer[types.struct_Synth], /) -> int: ...

    class anon_function_3(_CDataBase):
        ''' function pointer type:
        .. code-block:: c
            int(*)(struct Synth *, char *) '''
        def __call__(self, arg1: Pointer[types.struct_Synth], arg2: Union[Pointer[types.char], bytes], /) -> int: ...

    class anon_function_4(_CDataBase):
        ''' function pointer type:
        .. code-block:: c
            int(*)(struct Synth *, char *, int, int *) '''
        def __call__(self, arg1: Pointer[types.struct_Synth], arg2: Union[Pointer[types.char], bytes], arg3: int, arg4: Pointer[int], /) -> int: ...

    class anon_function_5(_CDataBase):
        ''' function pointer type:
        .. code-block:: c
            int(*)(struct Synth *, _Bool) '''
        def __call__(self, arg1: Pointer[types.struct_Synth], arg2: bool, /) -> int: ...

    class anon_function_6(_CDataBase):
        ''' function pointer type:
        .. code-block:: c
            int(*)(struct Synth *, void(*)(int, short *, void *), void *) '''
        def __call__(self, arg1: Pointer[types.struct_Synth], arg2: types.SynthAudioCb, arg3: PointerBase[object], /) -> int: ...

    class anon_function_7(_CDataBase):
        ''' function pointer type:
        .. code-block:: c
            void(*)(struct Synth *, void(*)(int, void *), void *) '''
        def __call__(self, arg1: Pointer[types.struct_Synth], arg2: types.anon_function_0, arg3: PointerBase[object], /) -> None: ...

    class anon_function_8(_CDataBase):
        ''' function pointer type:
        .. code-block:: c
            void(*)(struct Synth *, void(*)(char *, int, void *), void *) '''
        def __call__(self, arg1: Pointer[types.struct_Synth], arg2: types.SynthPhonemeCb, arg3: PointerBase[object], /) -> None: ...

    class anon_function_9(_CDataBase):
        ''' function pointer type:
        .. code-block:: c
            void(*)(struct Synth *, void(*)(enum SynthParamId, int, void *), void *) '''
        def __call__(self, arg1: Pointer[types.struct_Synth], arg2: types.SynthParamCb, arg3: PointerBase[object], /) -> None: ...

    class anon_function_10(_CDataBase):
        ''' function pointer type:
        .. code-block:: c
            int(*)(struct Synth *, int) '''
        def __call__(self, arg1: Pointer[types.struct_Synth], arg2: int, /) -> int: ...

    class anon_function_11(_CDataBase):
        ''' function pointer type:
        .. code-block:: c
            int(*)(struct Synth *, int, int) '''
        def __call__(self, arg1: Pointer[types.struct_Synth], arg2: int, arg3: int, /) -> int: ...

    class anon_function_12(_CDataBase):
        ''' function pointer type:
        .. code-block:: c
            void(*)(struct Synth *, _Bool) '''
        def __call__(self, arg1: Pointer[types.struct_Synth], arg2: bool, /) -> None: ...

    class anon_function_13(_CDataBase):
        ''' function pointer type:
        .. code-block:: c
            struct _SynthDict *(*)(struct Synth *) '''
        def __call__(self, arg1: Pointer[types.struct_Synth], /) -> PointerBase[types.struct__SynthDict]: ...

    class anon_function_14(_CDataBase):
        ''' function pointer type:
        .. code-block:: c
            void(*)(struct Synth *, struct _SynthDict *) '''
        def __call__(self, arg1: Pointer[types.struct_Synth], arg2: PointerBase[types.struct__SynthDict], /) -> None: ...

    class anon_function_15(_CDataBase):
        ''' function pointer type:
        .. code-block:: c
            void(*)(struct Synth *, struct _SynthDict *, enum SynthDictVolume, char *) '''
        def __call__(self, arg1: Pointer[types.struct_Synth], arg2: PointerBase[types.struct__SynthDict], arg3: types.enum_SynthDictVolume, arg4: Union[Pointer[types.char], bytes], /) -> None: ...

    class anon_function_16(_CDataBase):
        ''' function pointer type:
        .. code-block:: c
            int(*)(struct Synth *, struct _SynthDict *, enum SynthDictVolume, char *, char *) '''
        def __call__(self, arg1: Pointer[types.struct_Synth], arg2: PointerBase[types.struct__SynthDict], arg3: types.enum_SynthDictVolume, arg4: Union[Pointer[types.char], bytes], arg5: Union[Pointer[types.char], bytes], /) -> int: ...

    class anon_function_17(_CDataBase):
        ''' function pointer type:
        .. code-block:: c
            void(*)(struct Synth *, struct _SynthDict *, enum SynthDictVolume, char * *, char * *) '''
        def __call__(self, arg1: Pointer[types.struct_Synth], arg2: PointerBase[types.struct__SynthDict], arg3: types.enum_SynthDictVolume, arg4: Pointer[Pointer[types.char]], arg5: Pointer[Pointer[types.char]], /) -> None: ...

    class anon_function_18(_CDataBase):
        ''' function pointer type:
        .. code-block:: c
            char *(*)(struct Synth *, struct _SynthDict *, enum SynthDictVolume, char *) '''
        def __call__(self, arg1: Pointer[types.struct_Synth], arg2: PointerBase[types.struct__SynthDict], arg3: types.enum_SynthDictVolume, arg4: Union[Pointer[types.char], bytes], /) -> Pointer[types.char]: ...

    class anon_function_19(_CDataBase):
        ''' function pointer type:
        .. code-block:: c
            void(*)(struct Synth *, void(*)(void *), void *) '''
        def __call__(self, arg1: Pointer[types.struct_Synth], arg2: types.SynthUserIndexCb, arg3: PointerBase[object], /) -> None: ...

    class SynthUserIndexCb(_CDataBase):
        ''' function pointer type:
        .. code-block:: c
            void(*)(void *) '''
        def __call__(self, arg1: PointerBase[object], /) -> None: ...

    class sym_getObject(_CDataBase):
        ''' function pointer type:
        .. code-block:: c
            void(*)(int, struct Synth * *) '''
        def __call__(self, arg1: int, arg2: Pointer[Pointer[types.struct_Synth]], /) -> None: ...

class Lib:
    dictAbbv: types.enum_SynthDictVolume = 2
    ''' enum SynthDictVolume (value 2) '''

    dictMain: types.enum_SynthDictVolume = 0
    ''' enum SynthDictVolume (value 0) '''

    dictRoot: types.enum_SynthDictVolume = 1
    ''' enum SynthDictVolume (value 1) '''

    @property
    def getObject(self) -> types.sym_getObject:
        ''' function:
        .. code-block:: c
            void getObject(int, struct Synth * *); '''
        ...

class FFI(_cffi_backend.FFI):
    CData: TypeAlias = _CDataBase
    buffer: TypeAlias = _tmp_buffer  # noqa: Y042

    NULL: PointerBase[object]

    def dlclose(self, lib: Lib, /) -> None: ...
    if sys.platform == "win32":
        def dlopen(self, libpath: str | FFI.CData, flags: int = ..., /) -> Lib: ...
    else:
        def dlopen(self, libpath: str | FFI.CData | None = ..., flags: int = ..., /) -> Lib: ...

    def gc[T: CData](self, cdata: T, destructor: Callable[[T], Any], size: int = ...) -> T: ...

    @overload
    def new(self, ctype: Literal['int *'], init: int = ..., /) -> Pointer[int]: ...
    @overload
    def new(self, ctype: Literal['int[]'], init: Union[int, tuple[int, ...]], /) -> Array[int]: ...
    @overload
    def new(self, ctype: Literal['short *'], init: types.short = ..., /) -> Pointer[types.short]: ...
    @overload
    def new(self, ctype: Literal['short[]'], init: Union[int, tuple[types.short, ...]], /) -> Array[types.short]: ...
    @overload
    def new(self, ctype: Literal['short * *'], init: Pointer[types.short] = ..., /) -> Pointer[Pointer[types.short]]: ...
    @overload
    def new(self, ctype: Literal['short *[]'], init: Union[int, tuple[Pointer[types.short], ...]], /) -> Array[Pointer[types.short]]: ...
    @overload
    def new(self, ctype: Literal['void * *'], init: PointerBase[object] = ..., /) -> Pointer[PointerBase[object]]: ...
    @overload
    def new(self, ctype: Literal['void *[]'], init: Union[int, tuple[PointerBase[object], ...]], /) -> Array[PointerBase[object]]: ...
    @overload
    def new(self, ctype: Literal['void(* *)(int, short *, void *)'], init: types.SynthAudioCb = ..., /) -> Pointer[types.SynthAudioCb]: ...
    @overload
    def new(self, ctype: Literal['void(*[])(int, short *, void *)'], init: Union[int, tuple[types.SynthAudioCb, ...]], /) -> Array[types.SynthAudioCb]: ...
    @overload
    def new(self, ctype: Literal['struct _SynthDict * *'], init: PointerBase[types.struct__SynthDict] = ..., /) -> Pointer[PointerBase[types.struct__SynthDict]]: ...
    @overload
    def new(self, ctype: Literal['struct _SynthDict *[]'], init: Union[int, tuple[PointerBase[types.struct__SynthDict], ...]], /) -> Array[PointerBase[types.struct__SynthDict]]: ...
    @overload
    def new(self, ctype: Literal['char *', 'SynthDictStr'], init: types.char = ..., /) -> Pointer[types.char]: ...
    @overload
    def new(self, ctype: Literal['char[]'], init: Union[int, Union[bytes, tuple[types.char, ...]]], /) -> Array[types.char]: ...
    @overload
    def new(self, ctype: Literal['char * *'], init: Pointer[types.char] = ..., /) -> Pointer[Pointer[types.char]]: ...
    @overload
    def new(self, ctype: Literal['char *[]'], init: Union[int, tuple[Pointer[types.char], ...]], /) -> Array[Pointer[types.char]]: ...
    @overload
    def new(self, ctype: Literal['enum SynthDictVolume *'], init: types.enum_SynthDictVolume = ..., /) -> Pointer[types.enum_SynthDictVolume]: ...
    @overload
    def new(self, ctype: Literal['enum SynthDictVolume[]'], init: Union[int, tuple[types.enum_SynthDictVolume, ...]], /) -> Array[types.enum_SynthDictVolume]: ...
    @overload
    def new(self, ctype: Literal['void(* *)(int, void *)'], init: types.anon_function_0 = ..., /) -> Pointer[types.anon_function_0]: ...
    @overload
    def new(self, ctype: Literal['void(*[])(int, void *)'], init: Union[int, tuple[types.anon_function_0, ...]], /) -> Array[types.anon_function_0]: ...
    @overload
    def new(self, ctype: Literal['enum SynthParamId *'], init: types.enum_SynthParamId = ..., /) -> Pointer[types.enum_SynthParamId]: ...
    @overload
    def new(self, ctype: Literal['enum SynthParamId[]'], init: Union[int, tuple[types.enum_SynthParamId, ...]], /) -> Array[types.enum_SynthParamId]: ...
    @overload
    def new(self, ctype: Literal['void(* *)(enum SynthParamId, int, void *)'], init: types.SynthParamCb = ..., /) -> Pointer[types.SynthParamCb]: ...
    @overload
    def new(self, ctype: Literal['void(*[])(enum SynthParamId, int, void *)'], init: Union[int, tuple[types.SynthParamCb, ...]], /) -> Array[types.SynthParamCb]: ...
    @overload
    def new(self, ctype: Literal['void(* *)(char *, int, void *)'], init: types.SynthPhonemeCb = ..., /) -> Pointer[types.SynthPhonemeCb]: ...
    @overload
    def new(self, ctype: Literal['void(*[])(char *, int, void *)'], init: Union[int, tuple[types.SynthPhonemeCb, ...]], /) -> Array[types.SynthPhonemeCb]: ...
    @overload
    def new(self, ctype: Literal['struct Synth *', 'SynthPtr'], init: types.struct_Synth = ..., /) -> Pointer[types.struct_Synth]: ...
    @overload
    def new(self, ctype: Literal['struct Synth_vtable *'], init: types.struct_Synth_vtable = ..., /) -> Pointer[types.struct_Synth_vtable]: ...
    @overload
    def new(self, ctype: Literal['void(* *)(struct Synth *)'], init: types.anon_function_1 = ..., /) -> Pointer[types.anon_function_1]: ...
    @overload
    def new(self, ctype: Literal['void(*[])(struct Synth *)'], init: Union[int, tuple[types.anon_function_1, ...]], /) -> Array[types.anon_function_1]: ...
    @overload
    def new(self, ctype: Literal['int(* *)(struct Synth *)'], init: types.anon_function_2 = ..., /) -> Pointer[types.anon_function_2]: ...
    @overload
    def new(self, ctype: Literal['int(*[])(struct Synth *)'], init: Union[int, tuple[types.anon_function_2, ...]], /) -> Array[types.anon_function_2]: ...
    @overload
    def new(self, ctype: Literal['int(* *)(struct Synth *, char *)'], init: types.anon_function_3 = ..., /) -> Pointer[types.anon_function_3]: ...
    @overload
    def new(self, ctype: Literal['int(*[])(struct Synth *, char *)'], init: Union[int, tuple[types.anon_function_3, ...]], /) -> Array[types.anon_function_3]: ...
    @overload
    def new(self, ctype: Literal['int(* *)(struct Synth *, char *, int, int *)'], init: types.anon_function_4 = ..., /) -> Pointer[types.anon_function_4]: ...
    @overload
    def new(self, ctype: Literal['int(*[])(struct Synth *, char *, int, int *)'], init: Union[int, tuple[types.anon_function_4, ...]], /) -> Array[types.anon_function_4]: ...
    @overload
    def new(self, ctype: Literal['_Bool *'], init: bool = ..., /) -> Pointer[bool]: ...
    @overload
    def new(self, ctype: Literal['_Bool[]'], init: Union[int, tuple[bool, ...]], /) -> Array[bool]: ...
    @overload
    def new(self, ctype: Literal['int(* *)(struct Synth *, _Bool)'], init: types.anon_function_5 = ..., /) -> Pointer[types.anon_function_5]: ...
    @overload
    def new(self, ctype: Literal['int(*[])(struct Synth *, _Bool)'], init: Union[int, tuple[types.anon_function_5, ...]], /) -> Array[types.anon_function_5]: ...
    @overload
    def new(self, ctype: Literal['int(* *)(struct Synth *, void(*)(int, short *, void *), void *)'], init: types.anon_function_6 = ..., /) -> Pointer[types.anon_function_6]: ...
    @overload
    def new(self, ctype: Literal['int(*[])(struct Synth *, void(*)(int, short *, void *), void *)'], init: Union[int, tuple[types.anon_function_6, ...]], /) -> Array[types.anon_function_6]: ...
    @overload
    def new(self, ctype: Literal['void(* *)(struct Synth *, void(*)(int, void *), void *)'], init: types.anon_function_7 = ..., /) -> Pointer[types.anon_function_7]: ...
    @overload
    def new(self, ctype: Literal['void(*[])(struct Synth *, void(*)(int, void *), void *)'], init: Union[int, tuple[types.anon_function_7, ...]], /) -> Array[types.anon_function_7]: ...
    @overload
    def new(self, ctype: Literal['void(* *)(struct Synth *, void(*)(char *, int, void *), void *)'], init: types.anon_function_8 = ..., /) -> Pointer[types.anon_function_8]: ...
    @overload
    def new(self, ctype: Literal['void(*[])(struct Synth *, void(*)(char *, int, void *), void *)'], init: Union[int, tuple[types.anon_function_8, ...]], /) -> Array[types.anon_function_8]: ...
    @overload
    def new(self, ctype: Literal['void(* *)(struct Synth *, void(*)(enum SynthParamId, int, void *), void *)'], init: types.anon_function_9 = ..., /) -> Pointer[types.anon_function_9]: ...
    @overload
    def new(self, ctype: Literal['void(*[])(struct Synth *, void(*)(enum SynthParamId, int, void *), void *)'], init: Union[int, tuple[types.anon_function_9, ...]], /) -> Array[types.anon_function_9]: ...
    @overload
    def new(self, ctype: Literal['int(* *)(struct Synth *, int)'], init: types.anon_function_10 = ..., /) -> Pointer[types.anon_function_10]: ...
    @overload
    def new(self, ctype: Literal['int(*[])(struct Synth *, int)'], init: Union[int, tuple[types.anon_function_10, ...]], /) -> Array[types.anon_function_10]: ...
    @overload
    def new(self, ctype: Literal['int(* *)(struct Synth *, int, int)'], init: types.anon_function_11 = ..., /) -> Pointer[types.anon_function_11]: ...
    @overload
    def new(self, ctype: Literal['int(*[])(struct Synth *, int, int)'], init: Union[int, tuple[types.anon_function_11, ...]], /) -> Array[types.anon_function_11]: ...
    @overload
    def new(self, ctype: Literal['void(* *)(struct Synth *, _Bool)'], init: types.anon_function_12 = ..., /) -> Pointer[types.anon_function_12]: ...
    @overload
    def new(self, ctype: Literal['void(*[])(struct Synth *, _Bool)'], init: Union[int, tuple[types.anon_function_12, ...]], /) -> Array[types.anon_function_12]: ...
    @overload
    def new(self, ctype: Literal['struct _SynthDict *(* *)(struct Synth *)'], init: types.anon_function_13 = ..., /) -> Pointer[types.anon_function_13]: ...
    @overload
    def new(self, ctype: Literal['struct _SynthDict *(*[])(struct Synth *)'], init: Union[int, tuple[types.anon_function_13, ...]], /) -> Array[types.anon_function_13]: ...
    @overload
    def new(self, ctype: Literal['void(* *)(struct Synth *, struct _SynthDict *)'], init: types.anon_function_14 = ..., /) -> Pointer[types.anon_function_14]: ...
    @overload
    def new(self, ctype: Literal['void(*[])(struct Synth *, struct _SynthDict *)'], init: Union[int, tuple[types.anon_function_14, ...]], /) -> Array[types.anon_function_14]: ...
    @overload
    def new(self, ctype: Literal['void(* *)(struct Synth *, struct _SynthDict *, enum SynthDictVolume, char *)'], init: types.anon_function_15 = ..., /) -> Pointer[types.anon_function_15]: ...
    @overload
    def new(self, ctype: Literal['void(*[])(struct Synth *, struct _SynthDict *, enum SynthDictVolume, char *)'], init: Union[int, tuple[types.anon_function_15, ...]], /) -> Array[types.anon_function_15]: ...
    @overload
    def new(self, ctype: Literal['int(* *)(struct Synth *, struct _SynthDict *, enum SynthDictVolume, char *, char *)'], init: types.anon_function_16 = ..., /) -> Pointer[types.anon_function_16]: ...
    @overload
    def new(self, ctype: Literal['int(*[])(struct Synth *, struct _SynthDict *, enum SynthDictVolume, char *, char *)'], init: Union[int, tuple[types.anon_function_16, ...]], /) -> Array[types.anon_function_16]: ...
    @overload
    def new(self, ctype: Literal['void(* *)(struct Synth *, struct _SynthDict *, enum SynthDictVolume, char * *, char * *)'], init: types.anon_function_17 = ..., /) -> Pointer[types.anon_function_17]: ...
    @overload
    def new(self, ctype: Literal['void(*[])(struct Synth *, struct _SynthDict *, enum SynthDictVolume, char * *, char * *)'], init: Union[int, tuple[types.anon_function_17, ...]], /) -> Array[types.anon_function_17]: ...
    @overload
    def new(self, ctype: Literal['char *(* *)(struct Synth *, struct _SynthDict *, enum SynthDictVolume, char *)'], init: types.anon_function_18 = ..., /) -> Pointer[types.anon_function_18]: ...
    @overload
    def new(self, ctype: Literal['char *(*[])(struct Synth *, struct _SynthDict *, enum SynthDictVolume, char *)'], init: Union[int, tuple[types.anon_function_18, ...]], /) -> Array[types.anon_function_18]: ...
    @overload
    def new(self, ctype: Literal['void(* *)(void *)'], init: types.SynthUserIndexCb = ..., /) -> Pointer[types.SynthUserIndexCb]: ...
    @overload
    def new(self, ctype: Literal['void(*[])(void *)'], init: Union[int, tuple[types.SynthUserIndexCb, ...]], /) -> Array[types.SynthUserIndexCb]: ...
    @overload
    def new(self, ctype: Literal['void(* *)(struct Synth *, void(*)(void *), void *)'], init: types.anon_function_19 = ..., /) -> Pointer[types.anon_function_19]: ...
    @overload
    def new(self, ctype: Literal['void(*[])(struct Synth *, void(*)(void *), void *)'], init: Union[int, tuple[types.anon_function_19, ...]], /) -> Array[types.anon_function_19]: ...
    @overload
    def new(self, ctype: Literal['struct Synth_vtable[]'], init: Union[int, tuple[types.struct_Synth_vtable, ...]], /) -> Array[types.struct_Synth_vtable]: ...
    @overload
    def new(self, ctype: Literal['struct Synth_vtable * *'], init: Pointer[types.struct_Synth_vtable] = ..., /) -> Pointer[Pointer[types.struct_Synth_vtable]]: ...
    @overload
    def new(self, ctype: Literal['struct Synth_vtable *[]'], init: Union[int, tuple[Pointer[types.struct_Synth_vtable], ...]], /) -> Array[Pointer[types.struct_Synth_vtable]]: ...
    @overload
    def new(self, ctype: Literal['struct Synth[]'], init: Union[int, tuple[types.struct_Synth, ...]], /) -> Array[types.struct_Synth]: ...
    @overload
    def new(self, ctype: Literal['struct Synth * *'], init: Pointer[types.struct_Synth] = ..., /) -> Pointer[Pointer[types.struct_Synth]]: ...
    @overload
    def new(self, ctype: Literal['struct Synth *[]'], init: Union[int, tuple[Pointer[types.struct_Synth], ...]], /) -> Array[Pointer[types.struct_Synth]]: ...
    @overload
    def new(self, ctype: Literal['void(* *)(int, struct Synth * *)'], init: types.sym_getObject = ..., /) -> Pointer[types.sym_getObject]: ...
    @overload
    def new(self, ctype: Literal['void(*[])(int, struct Synth * *)'], init: Union[int, tuple[types.sym_getObject, ...]], /) -> Array[types.sym_getObject]: ...

    @overload
    def callback(self, ctype: Literal['void(*)(int, short *, void *)', 'SynthAudioCb'], error: Any = ..., onerror: ErrorCallback = ...) -> Callable[[Callable[[int, Pointer[types.short], PointerBase[object]], None]], types.SynthAudioCb]: ...
    @overload
    def callback(self, ctype: Literal['void(*)(int, void *)', 'SynthEventCb', 'SynthTextIndexCb', 'SynthWordIndexCb'], error: Any = ..., onerror: ErrorCallback = ...) -> Callable[[Callable[[int, PointerBase[object]], None]], types.anon_function_0]: ...
    @overload
    def callback(self, ctype: Literal['void(*)(enum SynthParamId, int, void *)', 'SynthParamCb'], error: Any = ..., onerror: ErrorCallback = ...) -> Callable[[Callable[[types.enum_SynthParamId, int, PointerBase[object]], None]], types.SynthParamCb]: ...
    @overload
    def callback(self, ctype: Literal['void(*)(char *, int, void *)', 'SynthPhonemeCb'], error: Any = ..., onerror: ErrorCallback = ...) -> Callable[[Callable[[Pointer[types.char], int, PointerBase[object]], None]], types.SynthPhonemeCb]: ...
    @overload
    def callback(self, ctype: Literal['void(*)(struct Synth *)'], error: Any = ..., onerror: ErrorCallback = ...) -> Callable[[Callable[[Pointer[types.struct_Synth]], None]], types.anon_function_1]: ...
    @overload
    def callback(self, ctype: Literal['int(*)(struct Synth *)'], error: Any = ..., onerror: ErrorCallback = ...) -> Callable[[Callable[[Pointer[types.struct_Synth]], int]], types.anon_function_2]: ...
    @overload
    def callback(self, ctype: Literal['int(*)(struct Synth *, char *)'], error: Any = ..., onerror: ErrorCallback = ...) -> Callable[[Callable[[Pointer[types.struct_Synth], Pointer[types.char]], int]], types.anon_function_3]: ...
    @overload
    def callback(self, ctype: Literal['int(*)(struct Synth *, char *, int, int *)'], error: Any = ..., onerror: ErrorCallback = ...) -> Callable[[Callable[[Pointer[types.struct_Synth], Pointer[types.char], int, Pointer[int]], int]], types.anon_function_4]: ...
    @overload
    def callback(self, ctype: Literal['int(*)(struct Synth *, _Bool)'], error: Any = ..., onerror: ErrorCallback = ...) -> Callable[[Callable[[Pointer[types.struct_Synth], bool], int]], types.anon_function_5]: ...
    @overload
    def callback(self, ctype: Literal['int(*)(struct Synth *, void(*)(int, short *, void *), void *)'], error: Any = ..., onerror: ErrorCallback = ...) -> Callable[[Callable[[Pointer[types.struct_Synth], types.SynthAudioCb, PointerBase[object]], int]], types.anon_function_6]: ...
    @overload
    def callback(self, ctype: Literal['void(*)(struct Synth *, void(*)(int, void *), void *)'], error: Any = ..., onerror: ErrorCallback = ...) -> Callable[[Callable[[Pointer[types.struct_Synth], types.anon_function_0, PointerBase[object]], None]], types.anon_function_7]: ...
    @overload
    def callback(self, ctype: Literal['void(*)(struct Synth *, void(*)(char *, int, void *), void *)'], error: Any = ..., onerror: ErrorCallback = ...) -> Callable[[Callable[[Pointer[types.struct_Synth], types.SynthPhonemeCb, PointerBase[object]], None]], types.anon_function_8]: ...
    @overload
    def callback(self, ctype: Literal['void(*)(struct Synth *, void(*)(enum SynthParamId, int, void *), void *)'], error: Any = ..., onerror: ErrorCallback = ...) -> Callable[[Callable[[Pointer[types.struct_Synth], types.SynthParamCb, PointerBase[object]], None]], types.anon_function_9]: ...
    @overload
    def callback(self, ctype: Literal['int(*)(struct Synth *, int)'], error: Any = ..., onerror: ErrorCallback = ...) -> Callable[[Callable[[Pointer[types.struct_Synth], int], int]], types.anon_function_10]: ...
    @overload
    def callback(self, ctype: Literal['int(*)(struct Synth *, int, int)'], error: Any = ..., onerror: ErrorCallback = ...) -> Callable[[Callable[[Pointer[types.struct_Synth], int, int], int]], types.anon_function_11]: ...
    @overload
    def callback(self, ctype: Literal['void(*)(struct Synth *, _Bool)'], error: Any = ..., onerror: ErrorCallback = ...) -> Callable[[Callable[[Pointer[types.struct_Synth], bool], None]], types.anon_function_12]: ...
    @overload
    def callback(self, ctype: Literal['struct _SynthDict *(*)(struct Synth *)'], error: Any = ..., onerror: ErrorCallback = ...) -> Callable[[Callable[[Pointer[types.struct_Synth]], PointerBase[types.struct__SynthDict]]], types.anon_function_13]: ...
    @overload
    def callback(self, ctype: Literal['void(*)(struct Synth *, struct _SynthDict *)'], error: Any = ..., onerror: ErrorCallback = ...) -> Callable[[Callable[[Pointer[types.struct_Synth], PointerBase[types.struct__SynthDict]], None]], types.anon_function_14]: ...
    @overload
    def callback(self, ctype: Literal['void(*)(struct Synth *, struct _SynthDict *, enum SynthDictVolume, char *)'], error: Any = ..., onerror: ErrorCallback = ...) -> Callable[[Callable[[Pointer[types.struct_Synth], PointerBase[types.struct__SynthDict], types.enum_SynthDictVolume, Pointer[types.char]], None]], types.anon_function_15]: ...
    @overload
    def callback(self, ctype: Literal['int(*)(struct Synth *, struct _SynthDict *, enum SynthDictVolume, char *, char *)'], error: Any = ..., onerror: ErrorCallback = ...) -> Callable[[Callable[[Pointer[types.struct_Synth], PointerBase[types.struct__SynthDict], types.enum_SynthDictVolume, Pointer[types.char], Pointer[types.char]], int]], types.anon_function_16]: ...
    @overload
    def callback(self, ctype: Literal['void(*)(struct Synth *, struct _SynthDict *, enum SynthDictVolume, char * *, char * *)'], error: Any = ..., onerror: ErrorCallback = ...) -> Callable[[Callable[[Pointer[types.struct_Synth], PointerBase[types.struct__SynthDict], types.enum_SynthDictVolume, Pointer[Pointer[types.char]], Pointer[Pointer[types.char]]], None]], types.anon_function_17]: ...
    @overload
    def callback(self, ctype: Literal['char *(*)(struct Synth *, struct _SynthDict *, enum SynthDictVolume, char *)'], error: Any = ..., onerror: ErrorCallback = ...) -> Callable[[Callable[[Pointer[types.struct_Synth], PointerBase[types.struct__SynthDict], types.enum_SynthDictVolume, Pointer[types.char]], Pointer[types.char]]], types.anon_function_18]: ...
    @overload
    def callback(self, ctype: Literal['void(*)(struct Synth *, void(*)(void *), void *)'], error: Any = ..., onerror: ErrorCallback = ...) -> Callable[[Callable[[Pointer[types.struct_Synth], types.SynthUserIndexCb, PointerBase[object]], None]], types.anon_function_19]: ...
    @overload
    def callback(self, ctype: Literal['void(*)(void *)', 'SynthUserIndexCb'], error: Any = ..., onerror: ErrorCallback = ...) -> Callable[[Callable[[PointerBase[object]], None]], types.SynthUserIndexCb]: ...
    @overload
    def callback(self, ctype: Literal['void(*)(int, struct Synth * *)'], error: Any = ..., onerror: ErrorCallback = ...) -> Callable[[Callable[[int, Pointer[Pointer[types.struct_Synth]]], None]], types.sym_getObject]: ...

    @overload
    def cast(self, ctype: Literal['_Bool', 'char', 'signed char', 'short', 'int', 'long', 'long long', 'unsigned char', 'unsigned short', 'unsigned int', 'unsigned long', 'unsigned long long', 'uint8_t', 'int8_t', 'int16_t', 'uint16_t', 'int32_t', 'uint32_t', 'int64_t', 'uint64_t', 'uintptr_t', 'intptr_t', 'ptrdiff_t', 'size_t', 'ssize_t', 'int_least8_t', 'uint_least8_t', 'int_least16_t', 'uint_least16_t', 'int_least32_t', 'uint_least32_t', 'int_least64_t', 'uint_least64_t', 'int_fast8_t', 'uint_fast8_t', 'int_fast16_t', 'uint_fast16_t', 'int_fast32_t', 'uint_fast32_t', 'int_fast64_t', 'uint_fast64_t', 'intmax_t', 'uintmax_t', 'wchar_t', 'char16_t', 'char32_t', 'bool'], value: Union[int, IntPrimitive, bool, float, FloatPrimitive, PointerBase[object]], /) -> IntPrimitive: ...
    @overload
    def cast(self, ctype: Literal['float', 'double', 'long double'], value: Union[int, IntPrimitive, bool, float, FloatPrimitive], /) -> FloatPrimitive: ...
    @overload
    def cast(self, ctype: Literal['float _Complex', 'double _Complex', '_cffi_float_complex_t', '_cffi_double_complex_t'], value: Union[complex, ComplexPrimitive, int, IntPrimitive, bool, float, FloatPrimitive], /) -> ComplexPrimitive: ...
    @overload
    def cast(self, ctype: Literal['enum SynthDictVolume', 'SynthDictVolume', 'enum SynthParamId'], value: Union[int, IntPrimitive, bool], /) -> EnumCData: ...
    @overload
    def cast(self, ctype: Literal['void(*)(int, short *, void *)', 'SynthAudioCb'], value: Union[int, IntPrimitive, PointerBase[object]], /) -> types.SynthAudioCb: ...
    @overload
    def cast(self, ctype: Literal['int *'], value: Union[int, IntPrimitive, PointerBase[object]], /) -> Pointer[int]: ...
    @overload
    def cast(self, ctype: Literal['short *'], value: Union[int, IntPrimitive, PointerBase[object]], /) -> Pointer[types.short]: ...
    @overload
    def cast(self, ctype: Literal['short * *'], value: Union[int, IntPrimitive, PointerBase[object]], /) -> Pointer[Pointer[types.short]]: ...
    @overload
    def cast(self, ctype: Literal['void *'], value: Union[int, IntPrimitive, PointerBase[object]], /) -> PointerBase[object]: ...
    @overload
    def cast(self, ctype: Literal['void * *'], value: Union[int, IntPrimitive, PointerBase[object]], /) -> Pointer[PointerBase[object]]: ...
    @overload
    def cast(self, ctype: Literal['void(* *)(int, short *, void *)'], value: Union[int, IntPrimitive, PointerBase[object]], /) -> Pointer[types.SynthAudioCb]: ...
    @overload
    def cast(self, ctype: Literal['struct _SynthDict *', 'SynthDict'], value: Union[int, IntPrimitive, PointerBase[object]], /) -> PointerBase[types.struct__SynthDict]: ...
    @overload
    def cast(self, ctype: Literal['struct _SynthDict * *'], value: Union[int, IntPrimitive, PointerBase[object]], /) -> Pointer[PointerBase[types.struct__SynthDict]]: ...
    @overload
    def cast(self, ctype: Literal['char *', 'SynthDictStr'], value: Union[int, IntPrimitive, PointerBase[object]], /) -> Pointer[types.char]: ...
    @overload
    def cast(self, ctype: Literal['char * *'], value: Union[int, IntPrimitive, PointerBase[object]], /) -> Pointer[Pointer[types.char]]: ...
    @overload
    def cast(self, ctype: Literal['enum SynthDictVolume *'], value: Union[int, IntPrimitive, PointerBase[object]], /) -> Pointer[types.enum_SynthDictVolume]: ...
    @overload
    def cast(self, ctype: Literal['void(*)(int, void *)', 'SynthEventCb', 'SynthTextIndexCb', 'SynthWordIndexCb'], value: Union[int, IntPrimitive, PointerBase[object]], /) -> types.anon_function_0: ...
    @overload
    def cast(self, ctype: Literal['void(* *)(int, void *)'], value: Union[int, IntPrimitive, PointerBase[object]], /) -> Pointer[types.anon_function_0]: ...
    @overload
    def cast(self, ctype: Literal['void(*)(enum SynthParamId, int, void *)', 'SynthParamCb'], value: Union[int, IntPrimitive, PointerBase[object]], /) -> types.SynthParamCb: ...
    @overload
    def cast(self, ctype: Literal['enum SynthParamId *'], value: Union[int, IntPrimitive, PointerBase[object]], /) -> Pointer[types.enum_SynthParamId]: ...
    @overload
    def cast(self, ctype: Literal['void(* *)(enum SynthParamId, int, void *)'], value: Union[int, IntPrimitive, PointerBase[object]], /) -> Pointer[types.SynthParamCb]: ...
    @overload
    def cast(self, ctype: Literal['void(*)(char *, int, void *)', 'SynthPhonemeCb'], value: Union[int, IntPrimitive, PointerBase[object]], /) -> types.SynthPhonemeCb: ...
    @overload
    def cast(self, ctype: Literal['void(* *)(char *, int, void *)'], value: Union[int, IntPrimitive, PointerBase[object]], /) -> Pointer[types.SynthPhonemeCb]: ...
    @overload
    def cast(self, ctype: Literal['struct Synth *', 'SynthPtr'], value: Union[int, IntPrimitive, PointerBase[object]], /) -> Pointer[types.struct_Synth]: ...
    @overload
    def cast(self, ctype: Literal['struct Synth_vtable *'], value: Union[int, IntPrimitive, PointerBase[object]], /) -> Pointer[types.struct_Synth_vtable]: ...
    @overload
    def cast(self, ctype: Literal['void(*)(struct Synth *)'], value: Union[int, IntPrimitive, PointerBase[object]], /) -> types.anon_function_1: ...
    @overload
    def cast(self, ctype: Literal['void(* *)(struct Synth *)'], value: Union[int, IntPrimitive, PointerBase[object]], /) -> Pointer[types.anon_function_1]: ...
    @overload
    def cast(self, ctype: Literal['int(*)(struct Synth *)'], value: Union[int, IntPrimitive, PointerBase[object]], /) -> types.anon_function_2: ...
    @overload
    def cast(self, ctype: Literal['int(* *)(struct Synth *)'], value: Union[int, IntPrimitive, PointerBase[object]], /) -> Pointer[types.anon_function_2]: ...
    @overload
    def cast(self, ctype: Literal['int(*)(struct Synth *, char *)'], value: Union[int, IntPrimitive, PointerBase[object]], /) -> types.anon_function_3: ...
    @overload
    def cast(self, ctype: Literal['int(* *)(struct Synth *, char *)'], value: Union[int, IntPrimitive, PointerBase[object]], /) -> Pointer[types.anon_function_3]: ...
    @overload
    def cast(self, ctype: Literal['int(*)(struct Synth *, char *, int, int *)'], value: Union[int, IntPrimitive, PointerBase[object]], /) -> types.anon_function_4: ...
    @overload
    def cast(self, ctype: Literal['int(* *)(struct Synth *, char *, int, int *)'], value: Union[int, IntPrimitive, PointerBase[object]], /) -> Pointer[types.anon_function_4]: ...
    @overload
    def cast(self, ctype: Literal['int(*)(struct Synth *, _Bool)'], value: Union[int, IntPrimitive, PointerBase[object]], /) -> types.anon_function_5: ...
    @overload
    def cast(self, ctype: Literal['_Bool *'], value: Union[int, IntPrimitive, PointerBase[object]], /) -> Pointer[bool]: ...
    @overload
    def cast(self, ctype: Literal['int(* *)(struct Synth *, _Bool)'], value: Union[int, IntPrimitive, PointerBase[object]], /) -> Pointer[types.anon_function_5]: ...
    @overload
    def cast(self, ctype: Literal['int(*)(struct Synth *, void(*)(int, short *, void *), void *)'], value: Union[int, IntPrimitive, PointerBase[object]], /) -> types.anon_function_6: ...
    @overload
    def cast(self, ctype: Literal['int(* *)(struct Synth *, void(*)(int, short *, void *), void *)'], value: Union[int, IntPrimitive, PointerBase[object]], /) -> Pointer[types.anon_function_6]: ...
    @overload
    def cast(self, ctype: Literal['void(*)(struct Synth *, void(*)(int, void *), void *)'], value: Union[int, IntPrimitive, PointerBase[object]], /) -> types.anon_function_7: ...
    @overload
    def cast(self, ctype: Literal['void(* *)(struct Synth *, void(*)(int, void *), void *)'], value: Union[int, IntPrimitive, PointerBase[object]], /) -> Pointer[types.anon_function_7]: ...
    @overload
    def cast(self, ctype: Literal['void(*)(struct Synth *, void(*)(char *, int, void *), void *)'], value: Union[int, IntPrimitive, PointerBase[object]], /) -> types.anon_function_8: ...
    @overload
    def cast(self, ctype: Literal['void(* *)(struct Synth *, void(*)(char *, int, void *), void *)'], value: Union[int, IntPrimitive, PointerBase[object]], /) -> Pointer[types.anon_function_8]: ...
    @overload
    def cast(self, ctype: Literal['void(*)(struct Synth *, void(*)(enum SynthParamId, int, void *), void *)'], value: Union[int, IntPrimitive, PointerBase[object]], /) -> types.anon_function_9: ...
    @overload
    def cast(self, ctype: Literal['void(* *)(struct Synth *, void(*)(enum SynthParamId, int, void *), void *)'], value: Union[int, IntPrimitive, PointerBase[object]], /) -> Pointer[types.anon_function_9]: ...
    @overload
    def cast(self, ctype: Literal['int(*)(struct Synth *, int)'], value: Union[int, IntPrimitive, PointerBase[object]], /) -> types.anon_function_10: ...
    @overload
    def cast(self, ctype: Literal['int(* *)(struct Synth *, int)'], value: Union[int, IntPrimitive, PointerBase[object]], /) -> Pointer[types.anon_function_10]: ...
    @overload
    def cast(self, ctype: Literal['int(*)(struct Synth *, int, int)'], value: Union[int, IntPrimitive, PointerBase[object]], /) -> types.anon_function_11: ...
    @overload
    def cast(self, ctype: Literal['int(* *)(struct Synth *, int, int)'], value: Union[int, IntPrimitive, PointerBase[object]], /) -> Pointer[types.anon_function_11]: ...
    @overload
    def cast(self, ctype: Literal['void(*)(struct Synth *, _Bool)'], value: Union[int, IntPrimitive, PointerBase[object]], /) -> types.anon_function_12: ...
    @overload
    def cast(self, ctype: Literal['void(* *)(struct Synth *, _Bool)'], value: Union[int, IntPrimitive, PointerBase[object]], /) -> Pointer[types.anon_function_12]: ...
    @overload
    def cast(self, ctype: Literal['struct _SynthDict *(*)(struct Synth *)'], value: Union[int, IntPrimitive, PointerBase[object]], /) -> types.anon_function_13: ...
    @overload
    def cast(self, ctype: Literal['struct _SynthDict *(* *)(struct Synth *)'], value: Union[int, IntPrimitive, PointerBase[object]], /) -> Pointer[types.anon_function_13]: ...
    @overload
    def cast(self, ctype: Literal['void(*)(struct Synth *, struct _SynthDict *)'], value: Union[int, IntPrimitive, PointerBase[object]], /) -> types.anon_function_14: ...
    @overload
    def cast(self, ctype: Literal['void(* *)(struct Synth *, struct _SynthDict *)'], value: Union[int, IntPrimitive, PointerBase[object]], /) -> Pointer[types.anon_function_14]: ...
    @overload
    def cast(self, ctype: Literal['void(*)(struct Synth *, struct _SynthDict *, enum SynthDictVolume, char *)'], value: Union[int, IntPrimitive, PointerBase[object]], /) -> types.anon_function_15: ...
    @overload
    def cast(self, ctype: Literal['void(* *)(struct Synth *, struct _SynthDict *, enum SynthDictVolume, char *)'], value: Union[int, IntPrimitive, PointerBase[object]], /) -> Pointer[types.anon_function_15]: ...
    @overload
    def cast(self, ctype: Literal['int(*)(struct Synth *, struct _SynthDict *, enum SynthDictVolume, char *, char *)'], value: Union[int, IntPrimitive, PointerBase[object]], /) -> types.anon_function_16: ...
    @overload
    def cast(self, ctype: Literal['int(* *)(struct Synth *, struct _SynthDict *, enum SynthDictVolume, char *, char *)'], value: Union[int, IntPrimitive, PointerBase[object]], /) -> Pointer[types.anon_function_16]: ...
    @overload
    def cast(self, ctype: Literal['void(*)(struct Synth *, struct _SynthDict *, enum SynthDictVolume, char * *, char * *)'], value: Union[int, IntPrimitive, PointerBase[object]], /) -> types.anon_function_17: ...
    @overload
    def cast(self, ctype: Literal['void(* *)(struct Synth *, struct _SynthDict *, enum SynthDictVolume, char * *, char * *)'], value: Union[int, IntPrimitive, PointerBase[object]], /) -> Pointer[types.anon_function_17]: ...
    @overload
    def cast(self, ctype: Literal['char *(*)(struct Synth *, struct _SynthDict *, enum SynthDictVolume, char *)'], value: Union[int, IntPrimitive, PointerBase[object]], /) -> types.anon_function_18: ...
    @overload
    def cast(self, ctype: Literal['char *(* *)(struct Synth *, struct _SynthDict *, enum SynthDictVolume, char *)'], value: Union[int, IntPrimitive, PointerBase[object]], /) -> Pointer[types.anon_function_18]: ...
    @overload
    def cast(self, ctype: Literal['void(*)(struct Synth *, void(*)(void *), void *)'], value: Union[int, IntPrimitive, PointerBase[object]], /) -> types.anon_function_19: ...
    @overload
    def cast(self, ctype: Literal['void(*)(void *)', 'SynthUserIndexCb'], value: Union[int, IntPrimitive, PointerBase[object]], /) -> types.SynthUserIndexCb: ...
    @overload
    def cast(self, ctype: Literal['void(* *)(void *)'], value: Union[int, IntPrimitive, PointerBase[object]], /) -> Pointer[types.SynthUserIndexCb]: ...
    @overload
    def cast(self, ctype: Literal['void(* *)(struct Synth *, void(*)(void *), void *)'], value: Union[int, IntPrimitive, PointerBase[object]], /) -> Pointer[types.anon_function_19]: ...
    @overload
    def cast(self, ctype: Literal['struct Synth_vtable * *'], value: Union[int, IntPrimitive, PointerBase[object]], /) -> Pointer[Pointer[types.struct_Synth_vtable]]: ...
    @overload
    def cast(self, ctype: Literal['struct Synth * *'], value: Union[int, IntPrimitive, PointerBase[object]], /) -> Pointer[Pointer[types.struct_Synth]]: ...
    @overload
    def cast(self, ctype: Literal['void(*)(int, struct Synth * *)'], value: Union[int, IntPrimitive, PointerBase[object]], /) -> types.sym_getObject: ...
    @overload
    def cast(self, ctype: Literal['void(* *)(int, struct Synth * *)'], value: Union[int, IntPrimitive, PointerBase[object]], /) -> Pointer[types.sym_getObject]: ...

    @overload
    def addressof[T](self, cdata: Pointer[T], index: int, /) -> Pointer[T]: ...
    @overload
    def addressof[T: _CDataBase](self, cdata: T, /) -> Pointer[T]: ...
    @overload
    def addressof(self, cdata: types.struct_Synth, field: Literal['vtable'], /) -> Pointer[Pointer[types.struct_Synth_vtable]]: ...
    @overload
    def addressof(self, cdata: types.struct_Synth_vtable, field: Literal['__method0'], /) -> Pointer[types.anon_function_1]: ...
    @overload
    def addressof(self, cdata: types.struct_Synth_vtable, field: Literal['__method1'], /) -> Pointer[types.anon_function_1]: ...
    @overload
    def addressof(self, cdata: types.struct_Synth_vtable, field: Literal['destroy'], /) -> Pointer[types.anon_function_1]: ...
    @overload
    def addressof(self, cdata: types.struct_Synth_vtable, field: Literal['init'], /) -> Pointer[types.anon_function_2]: ...
    @overload
    def addressof(self, cdata: types.struct_Synth_vtable, field: Literal['__method4'], /) -> Pointer[types.anon_function_1]: ...
    @overload
    def addressof(self, cdata: types.struct_Synth_vtable, field: Literal['pushText'], /) -> Pointer[types.anon_function_3]: ...
    @overload
    def addressof(self, cdata: types.struct_Synth_vtable, field: Literal['pushText2'], /) -> Pointer[types.anon_function_3]: ...
    @overload
    def addressof(self, cdata: types.struct_Synth_vtable, field: Literal['__method7'], /) -> Pointer[types.anon_function_1]: ...
    @overload
    def addressof(self, cdata: types.struct_Synth_vtable, field: Literal['__method8'], /) -> Pointer[types.anon_function_1]: ...
    @overload
    def addressof(self, cdata: types.struct_Synth_vtable, field: Literal['readPhonemes'], /) -> Pointer[types.anon_function_4]: ...
    @overload
    def addressof(self, cdata: types.struct_Synth_vtable, field: Literal['__method10'], /) -> Pointer[types.anon_function_1]: ...
    @overload
    def addressof(self, cdata: types.struct_Synth_vtable, field: Literal['setFlushing'], /) -> Pointer[types.anon_function_5]: ...
    @overload
    def addressof(self, cdata: types.struct_Synth_vtable, field: Literal['prepare'], /) -> Pointer[types.anon_function_2]: ...
    @overload
    def addressof(self, cdata: types.struct_Synth_vtable, field: Literal['__method13'], /) -> Pointer[types.anon_function_1]: ...
    @overload
    def addressof(self, cdata: types.struct_Synth_vtable, field: Literal['__method14'], /) -> Pointer[types.anon_function_1]: ...
    @overload
    def addressof(self, cdata: types.struct_Synth_vtable, field: Literal['__method15'], /) -> Pointer[types.anon_function_1]: ...
    @overload
    def addressof(self, cdata: types.struct_Synth_vtable, field: Literal['__method16'], /) -> Pointer[types.anon_function_1]: ...
    @overload
    def addressof(self, cdata: types.struct_Synth_vtable, field: Literal['setCallbackAudio'], /) -> Pointer[types.anon_function_6]: ...
    @overload
    def addressof(self, cdata: types.struct_Synth_vtable, field: Literal['__method18'], /) -> Pointer[types.anon_function_1]: ...
    @overload
    def addressof(self, cdata: types.struct_Synth_vtable, field: Literal['setCallbackTextIndex'], /) -> Pointer[types.anon_function_7]: ...
    @overload
    def addressof(self, cdata: types.struct_Synth_vtable, field: Literal['setCallbackEvent'], /) -> Pointer[types.anon_function_7]: ...
    @overload
    def addressof(self, cdata: types.struct_Synth_vtable, field: Literal['setCallbackPhoneme'], /) -> Pointer[types.anon_function_8]: ...
    @overload
    def addressof(self, cdata: types.struct_Synth_vtable, field: Literal['setCallbackParam'], /) -> Pointer[types.anon_function_9]: ...
    @overload
    def addressof(self, cdata: types.struct_Synth_vtable, field: Literal['pushEvent'], /) -> Pointer[types.anon_function_10]: ...
    @overload
    def addressof(self, cdata: types.struct_Synth_vtable, field: Literal['pushEventAt'], /) -> Pointer[types.anon_function_11]: ...
    @overload
    def addressof(self, cdata: types.struct_Synth_vtable, field: Literal['setWantWordIndices'], /) -> Pointer[types.anon_function_12]: ...
    @overload
    def addressof(self, cdata: types.struct_Synth_vtable, field: Literal['preDestruct'], /) -> Pointer[types.anon_function_1]: ...
    @overload
    def addressof(self, cdata: types.struct_Synth_vtable, field: Literal['dictNew'], /) -> Pointer[types.anon_function_13]: ...
    @overload
    def addressof(self, cdata: types.struct_Synth_vtable, field: Literal['__method28'], /) -> Pointer[types.anon_function_1]: ...
    @overload
    def addressof(self, cdata: types.struct_Synth_vtable, field: Literal['dictSetActive'], /) -> Pointer[types.anon_function_14]: ...
    @overload
    def addressof(self, cdata: types.struct_Synth_vtable, field: Literal['dictDelete'], /) -> Pointer[types.anon_function_14]: ...
    @overload
    def addressof(self, cdata: types.struct_Synth_vtable, field: Literal['dictLoad'], /) -> Pointer[types.anon_function_15]: ...
    @overload
    def addressof(self, cdata: types.struct_Synth_vtable, field: Literal['dictSave'], /) -> Pointer[types.anon_function_15]: ...
    @overload
    def addressof(self, cdata: types.struct_Synth_vtable, field: Literal['dictUpdate'], /) -> Pointer[types.anon_function_16]: ...
    @overload
    def addressof(self, cdata: types.struct_Synth_vtable, field: Literal['dictGetFirstEntry'], /) -> Pointer[types.anon_function_17]: ...
    @overload
    def addressof(self, cdata: types.struct_Synth_vtable, field: Literal['dictGetNextEntry'], /) -> Pointer[types.anon_function_17]: ...
    @overload
    def addressof(self, cdata: types.struct_Synth_vtable, field: Literal['dictLookup'], /) -> Pointer[types.anon_function_18]: ...
    @overload
    def addressof(self, cdata: types.struct_Synth_vtable, field: Literal['setCallbackWordIndex'], /) -> Pointer[types.anon_function_7]: ...
    @overload
    def addressof(self, cdata: types.struct_Synth_vtable, field: Literal['setCallbackUserIndex'], /) -> Pointer[types.anon_function_19]: ...

    @overload
    def string(self, cdata: Pointer[bytes], maxlength: int = -1) -> bytes: ...
    @overload
    def string(self, cdata: Pointer[str], maxlength: int = -1) -> str: ...
    @overload
    def string(self, cdata: EnumCData) -> str: ...

    @overload
    def unpack(self, cdata: Pointer[bytes], length: int) -> bytes: ...
    @overload
    def unpack(self, cdata: Pointer[str], length: int) -> str: ...
    @overload
    def unpack[T](self, cdata: Pointer[T], length: int) -> list[T]: ...

ffi: FFI
